resources:
  jobs:
    train_xgb_history_poisson:
      name: crimenet-${bundle.target}-xgb-history-poisson
      tasks:
        - task_key: train
          python_wheel_task:
            package_name: crimenet_ml
            entry_point: crimenet-train
            parameters:
              - --config
              - ${var.config_path}
              - --data-table
              - ${var.catalog}.gold.ml_spatiotemporal_examples_k5
              - --experiment-name
              - ${var.experiment_path}
          environment_key: default
      environments:
        - environment_key: default
          spec:
            client: "3"
            dependencies:
              - ../../dist/*.whl
