targets:
  staging:
    mode: production

    git:
      branch: main

    workspace:
      host: https://adb-7405618481105118.18.azuredatabricks.net
      root_path: /Workspace/Shared/.bundle/${bundle.name}/${bundle.target}

    variables:
      catalog: crimenet_staging
      raw_landing_path: /Volumes/crimenet_dev/raw_files/landing

    run_as:
      user_name: roshanaldrin@gmail.com

    permissions:
      - user_name: roshanaldrin@gmail.com
        level: CAN_MANAGE
